os:
  - osx

language: java

before_install:
  - brew update
  
install:
  - brew cask install google-chrome
  - brew install chromedriver
  - brew install gauge
  - npm install --global surge
  - gauge --install java
  - gauge --install html-report

cache:
  directories:
  - $HOME/.m2

script:
  - curl -L https://bintray.com/artifact/download/gauge/activeadmin-demo/activeadmin-demo.war -O
  - nohup java -jar activeadmin-demo.war >/dev/null 2>&1 &
  - sleep 30
  - mvn clean
  - mvn test
  
after_success:
  - cd ./reports/html-report 
  - surge

after_failure:
  - cd ./reports/html-report 
  - surge
